apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    run: python-docker-thedatabasengineer1
    name: python-docker-thedatabasengineer1
spec:
  nodeSelector:
    python: docker-thedatabasengineer
  containers:
  - image: python-docker-thedatabasengineer:latest
    imagePullPolicy: Never
    name: python-docker-thedatabasengineer1

  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  labels:
    app: python-docker-thedatabasengineer1
    name: python-docker-thedatabasengineer1
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32000
  selector:
    run: python-docker-thedatabasengineer1
  type: NodePort
